### ISSUE TITLE
Falha no build com o código mais recente

### ISSUE THREAD

**Issue by rafaelse** [spbgovbr/Sistema_Programa_de_Gestao_Susep#37]
O build no Docker/Linux está falhando com o código atual, emitindo as seguintes mensagens de erro:

```
ERROR in src/app/modules/programa-gestao/components/agendamento-presencial/agendamento-presencial.component.html(20,26): Property 'calendarWeekends' does not exist on type 'AgendamentoPresencialComponent'. Did you mean 'calendarEvents'?
  
/Sistema_Programa_de_Gestao_Susep/src/Susep.SISRH.WebApp/Susep.SISRH.WebApp.csproj(39,5): error MSB3073: The command "npm run build -- --prod" exited with code 1.

The command '/bin/sh -c dotnet publish --configuration Release' returned a non-zero code: 1
```
Até a atualização do código, o build funcionava normalmente.

**Comment by SrMouraSilva** [comment]
Aparentemente não mandaram o código fonte correto do `src/Susep.SISRH.WebApp/ClientApp/src/app/modules/programa-gestao/components/agendamento-presencial/agendamento-presencial.component.html` ou do `src/Susep.SISRH.WebApp/ClientApp/src/app/modules/programa-gestao/components/agendamento-presencial/agendamento-presencial.component.ts`

**Comment by rafaelse** [comment]
Problema resolvido após o commit https://github.com/spbgovbr/Sistema_Programa_de_Gestao_Susep/commit/e78c37d3ac376e82d6ee3a872a42f5903fecf219.
