### ISSUE TITLE
O vídeo da página README está privado

### ISSUE THREAD

**Issue by arturluizbr** [spbgovbr/Sistema_Programa_de_Gestao_Susep#45]
O link apresentado no arquivo [README.md](https://github.com/spbgovbr/Sistema_Programa_de_Gestao_Susep/blob/main/README.md) está marcado como privado, o que nos impede de vê-lo. O ideal seria marcá-lo como `não listado` para que apenas quem possua o link possa assistir.

```markdown
# README.md
Para entender os conceitos e principais funcionalidades, assista à apresentação disponível no seguinte link: 
https://youtu.be/VU_1TTAMg2Y
```

**Comment by andrealcantara** [comment]
Veja https://www.gov.br/servidor/pt-br/assuntos/programa-de-gestao

Boa parte das coisas está lá agora.
